"""[SPEC] Producers of OPDS Catalogs SHOULD produce OPDS Catalog Feed Documents and OPDS Catalog Entry Documents that are conformant to both Atom and the OPDS Catalog RELAX NG schemas"""
"""[SPEC] Each OPDS Catalog Feed Document SHOULD contain an atom:link element with a link relation of start, which references the OPDS Catalog Root Resource"""
"""[SPEC] [In a Navigation Feed] [e]ach Atom Entry's atom:content SHOULD include a brief description of the linked Resource"""
"""[SPEC] Links to Navigation Feeds SHOULD use the type attribute application/atom+xml;type=feed;profile=opds-catalog"""
"""[SPEC] The relation subsection SHOULD be used if no other relation [to a Navigation Feed] is more appropriate"""
"""[SPEC] Links to Acquisition Feeds SHOULD use the type attribute application/atom+xml;type=feed;profile=opds-catalog"""
"""[SPEC] OPDS Catalog Feed Documents SHOULD include links to other available Acquisition and Navigation Feeds and other related Resources"""
"""[SPEC] In an OpenSearch description document, the search interface SHOULD use the media type associated to OPDS Catalogs: application/atom+xml;type=feed;profile=opds-catalog"""
"""[SPEC] OPDS Catalog Feed Documents SHOULD contain one atom:link element with a rel attribute value of self"""
"""[SPEC] Partial Catalog Entries SHOULD include the following metadata elements, if available: atom:category, atom:rights, dc:extent, dc:identifier, dc:issued, dc:language, dc:publisher, and opds:price"""
"""[SPEC] [In an OPDS Catalog Entry] [o]ne or more dc:identifier elements SHOULD be used to identify the represented Publication, if appropriate metadata is available"""
"""[SPEC] [In an OPDS Catalog Entry] [a] dc:issued element SHOULD be used to indicate the first publication date of the Publication"""
"""[SPEC] OPDS Catalog Entries SHOULD use atom:author to represent the Publication's creators """
"""[SPEC] OPDS Catalog Entries SHOULD use atom:category to represent the Publication's category, keywords, key phrases, or classification codes """
"""[SPEC] OPDS Catalog Entries SHOULD use atom:rights to represent rights held in and over the Publication """
"""[SPEC] OPDS Catalog Entries SHOULD use atom:summary and/or atom:content to describe the Publication """
"""[SPEC] OPDS Catalog Entries SHOULD include either atom:summary or atom:content elements or both to provide a description, summary, abstract, or excerpt of the Publication"""
"""[SPEC] If an OPDS Catalog Entry includes both atom:content and atom:summary ... [b]oth elements SHOULD be included in the Complete Catalog Entry"""
"""[SPEC] OPDS Catalog Entry Documents SHOULD include links to related Entry Documents"""
"""[SPEC] The maximum size of the longest dimension of http://opds-spec.org/thumbnail images SHOULD be 120 pixels"""
"""[SPEC] If the Publication is available using Indirect Acquisition, the type attribute of the Acquisition Link SHOULD represent the media type of the first Resource a client must dereference to begin the acquisition"""
"""[SPEC] Publications in a format using Digital Rights Management SHOULD use a different value for the type attribute or dc:format child of the Acquisition Link than the same format without Digital Rights Management"""
"""[SPEC] OPDS Catalog providers SHOULD use Partial Catalog Entries in all Acquisition Feeds except Complete Acquisition Feeds"""
"""[SPEC] If available, each OPDS Catalog Feed Document in the OPDS Catalog SHOULD contain an atom:link element with a the relation of http://opds-spec.org/crawlable that references the Complete Acquisition Feed Resource"""
"""[SPEC] OPDS Catalog providers SHOULD use a compressed Content-Encoding when transmitting Complete Acquisition Feeds over HTTP"""
"""[SPEC] Publishers of OPDS Catalogs SHOULD use the type parameter"""
"""[SPEC] Relations to OPDS Catalog Feed Document and OPDS Catalog Entry Document Resources SHOULD use a profile parameter"""
"""[SPEC] The complete media type for a relation to an OPDS Catalog Entry Document Resource SHOULD be: application/atom+xml;type=entry;profile=opds-catalog"""
"""[SPEC] The complete media type for a relation to an OPDS Catalog Feed Document Resource SHOULD be: application/atom+xml;type=feed;profile=opds-catalog"""
