"""[SPEC] OPDS Catalog Feed Documents and OPDS Catalog Entry Documents MUST be "namespace-well-formed" """
"""[SPEC] Every OPDS Catalog Feed Document MUST either be an Acquisition Feed or a Navigation Feed"""
"""[SPEC] Every OPDS Catalog MUST have one and only one OPDS Catalog Root"""
"""[SPEC] Links to OpenSearch Description documents MUST use the search relation value"""
"""[SPEC] Links to OpenSearch Description documents MUST use ... the application/opensearchdescription+xml media type"""
"""[SPEC] Each OPDS Catalog Entry Document MUST include at least one Acquisition Link"""
"""[SPEC] A Partial Catalog Entry MUST include an alternate link relation referencing the Complete Catalog Entry Resource"""
"""[SPEC] A Partial Catalog Entry MUST include an alternate link relation ... and that atom:link MUST use the type attribute application/atom+xml;type=entry;profile=opds-catalog"""
"""[SPEC] Any Catalog Entry without a link to a Complete Catalog Entry MUST include all metadata elements"""
"""[SPEC] OPDS Catalog Entries MUST be identified by an atom:id"""
"""[SPEC] OPDS Catalog Entries MUST include an atom:updated element"""
"""[SPEC] OPDS Catalog Entries MUST inlcude an atom:title"""
"""[SPEC] An atom:id identifying an OPDS Catalog Entry ... MUST be created in a way that assures uniqueness"""
"""[SPEC] The content of an atom:summary element MUST be text"""
"""[SPEC] OPDS Catalog Entries [with] atom:links to images ... [and] [t]hese atom:links MUST use one of the following relations for these images: http://opds-spec.org/cover, http://opds-spec.org/thumbnail"""
"""[SPEC] OPDS Catalog Entries [with] atom:links to images ... MUST include a type attribute of image/gif, image/jpeg, or image/png"""
"""[SPEC] [I]mage Resources MUST be in GIF, JPEG, or PNG format [if linked from an OPDS Catalog Entry using one of the following relations for these images: http://opds-spec.org/cover, http://opds-spec.org/thumbnail]"""
"""[SPEC] atom:link elements with a rel attribute value of http://opds-spec.org/acquisition/buy MUST contain one opds:price element"""
"""[SPEC] On the opds:price element, the value of the currencycode attribute MUST be an Alphabetic code from ISO4217"""
"""[SPEC] All Acquisition Links MUST include a type attribute"""
"""[SPEC] All Acquisition Links MUST include a type attribute [and] ... the value of the type attribute MUST conform to the syntax of a MIME media type"""
"""[SPEC] If the Publication is available using Direct Acquisition, the type attribute of the Acquisition Link MUST represent the media type of the Publication Resource itself"""
"""[SPEC] For Acquisition Links using Direct Acquisition, the dc:format element MUST contain the same content value as the type parameter of its parent"""
"""[SPEC] [Acquisition Links using Indirect Acquisition] MUST contain one or more dc:format elements"""
"""[SPEC] [In] a Complete Acquisition Feed ... each OPDS Catalog Entry MUST be ordered by atom:updated, with the most recently updated Atom Entries coming first in the document order"""
"""[SPEC] A Complete Acquisition Feed MUST include a fh:complete element"""
"""[SPEC] OPDS Catalog providers MUST include Complete Catalog Entries when serializing a Complete Acquisition Feed"""
